### ISSUE TITLE
FAILED: Build did NOT complete successfully (Failed on step 7)

### ISSUE THREAD

**Issue by iziamtso** [sitting-duck/stuff#2]
I found 2 issues with this guide:
1)  In _Step 3: Install Python for Windows_
Last line is:
_Once you have installed Python for Windows, also install those dependencies in the screencap above._ I think the link to the screen capture is broken and I cannot see which dependencies are needed.

2) _In Step 7 (I have used conda python path and lib for step 3) :_
bazel build --config=cuda tensorflow:tensorflow.dll

ERROR: C:/tensorflow/tensorflow/BUILD:624:1 C++ compilation of rule '//tensorflow/core/lib/random:philox' failed (Exit 2): python.exe failed: error executing command

I followed your guide exactly. Do you have any idea what could be going on?

I would really appreciate any help on this.

**Comment by sitting-duck** [comment]
Hi there! Sorry for the delay in response. Just FYI I am most active on weekends. Feel free also to drop me a line at ashley.tharp@gmail.com. 

1. You are correct, step 3 was bad. I have made some changes to address this, please take a look at step 3 again and let me know if it is clear now. I updated the screen cap, and I also included a link to the TF documentation where I got the screencap. 

2. I have not enountered this exact error before when building, so I don't have a ready to go fix for this, however, I looked up Philox, and it appears to be a random number generator. In step 3 (the one with the missing screencap that I messed up) was the step ``pip3 install six numpy wheel``. numpy is a mathematics library, and since this part that failed was related to a random number generator, I will guess that these two things may be related. 

I don't think you need to start over at the very beginning of the guide. I think you can install numpy (and the other packages now shown in the screencap for step 3) and build tensorflow. If it still doesn't work I would do a whole rebuild just to make sure. If that doesn't work, please reach out to me on gmail, or create a new issue here with the new build error(s). 

Thanks for reporting this, I am glad someone is using it, that makes me so happy.

**Comment by sitting-duck** [comment]
Hey there, have you had a chance to work on this anymore?

**Comment by sitting-duck** [comment]
Hi there, just checking in again, did you ever get a chance to work on this project again? Please let me know, I'd be happy to correspond. You can reach out to ashley.tharp@gmail.com to discuss details that you aren't comfortable posting online if you like. I would be happy to correspond.

**Comment by sitting-duck** [comment]
User not responding many months after fix deployed. Will go ahead and close the issue.
